openapi: 3.0.0
info:
  title: Payment Service
  description: >
    `Design First`
  version: 1.0.0
servers:
  - url: /
tags:
  - name: Gateway
    description: Внешний API
  - name: DB
    description: API для микросервиса, работающего с БД
  - name: Activator
    description: API микросервиса для активации продуктов/услуг
  - name: Money increase service
    description: API микросервиса для списания со счета клиента/поставщика
  - name: Money decrease service
    description: API микросервиса для пополнения счета клиента/поставщика
security:
  - bearerAuth: []
paths:
  /pay:
    post:
      summary: Оплата продукта/услуги
      operationId: pay
      tags:
        - Gateway
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /cancel:
    post:
      summary: Отмена продукта/услуги
      operationId: cancel
      tags:
        - Gateway
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CancelingParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /deposit:
    post:
      summary: Внесение средств на счет клиента
      operationId: deposit
      tags:
        - Gateway
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /info:
    get:
      summary: Получение списка покупок по продукту
      operationId: findProductsByName
      tags:
        - Gateway
      parameters:
        - in: query
          name: product
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductContracts'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /clients/{clientId}:
    patch:
      summary: Изменение остатка на счету клиента
      operationId: clientsMoneyUpdate
      tags:
        - DB
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/ClientsUpdateParameters'
      parameters:
        - $ref: '#/components/parameters/clientId'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /suppliers/{supplierId}:
    patch:
      summary: Изменение остатка на счету поставщика
      operationId: suppliersMoneyUpdate
      tags:
        - DB
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/SuppliersUpdateParameters'
      parameters:
        - $ref: '#/components/parameters/supplierId'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/InternalServerError'
  /activate:
    post:
      summary: Активация продукта/услуги
      operationId: activate
      tags:
        - Activator
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/ActivateParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /deactivate:
    patch:
      summary: Отключение продукта/услуги
      operationId: deactivate
      tags:
        - Activator
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/DeactivateParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /increase-money:
    patch:
      summary: Списывает деньги со счета клиента/поставщика
      operationId: increase
      tags:
        - Money increase service
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/IncreasingParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'
  /decrease-money:
    patch:
      summary: Пополняет счет клиента/поставщика
      operationId: decrease
      tags:
        - Money decrease service
      requestBody:
        content:
          application/json:
            schema:
               $ref: '#/components/schemas/DeacreasingParameters'
      responses:
        200:
          description: OK
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        422:
          $ref: '#/components/responses/UnprocessableEntity'
        500:
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    clientId:
      name: clientId
      description: Идентификатор клиента
      required: true
      in: path
      schema:
        type: integer
        format: int64
    supplierId:
      name: supplierId
      description: Идентификатор поставщика
      required: true
      in: path
      schema:
        type: integer
        format: int64
  responses:
    BadRequest:
      description: Bad Request
    Unauthorized:
      description: Unauthorized
    Forbidden:
      description: Forbidden
    NotFound:
      description: Not Found
    UnprocessableEntity:
      description: Unprocessable Entity
    InternalServerError:
      description: Internal Server Error
  schemas:
    PaymentParameters:
      required:
        - clientId
        - sum
        - productName
      properties:
        clientId:
          description: Идентификатор клиента
          type: number
          format: int64
        sum:
          description: Стоимость продукта/услуги
          type: number
          format: int32
        productName:
          description: Наименование продукта
          type: string
    CancelingParameters:
      required:
        - clientId
        - productName
      properties:
        clientId:
          description: Идентификатор клиента
          type: number
          format: int64
        productName:
          description: Наименование продукта
          type: string
    DepositParameters:
      required:
        - clientId
        - sum
      properties:
        clientId:
          description: Идентификатор клиента
          type: number
          format: int64
        sum:
          description: Стоимость продукта/услуги
          type: number
          format: int32
    ProductContracts:
      required:
        - id
        - name
      properties:
        productName:
          description: Наименование продукта
          type: string
        clientName:
          description: Имя клиента
          type: string
        numberOfContracts:
          description: Кол-во покупок продукта/услуги
          type: number
          format: int32
    ClientsUpdateParameters:
      required:
        - sum
        - operationType
      properties:
        sum:
          description: Стоимость продукта/услуги (сумма для списания/пополнения)
          type: number
          format: int32
        operationType:
          $ref: '#/components/schemas/OperationType'
    SuppliersUpdateParameters:
      required:
        - sum
        - operationType
      properties:
        sum:
          description: Стоимость продукта/услуги
          type: number
          format: int32
        operationType:
          $ref: '#/components/schemas/OperationType'
    OperationType:
      description: >-
        Тип операции: пополнение или списание
      type: string
      enum:
        - credit # Списание
        - debit # Пополнение
    ActivateParameters:
      required:
        - clientId
        - productId
        - supplierId
      properties:
        clientId:
          description: Идентификатор клиента
          type: number
        productId:
          description: Идентификатор продукта/услуги
          type: number
          format: int64
        supplierId:
          description: Идентификатор поставщика
          type: number
          format: int64
    DeactivateParameters:
      required:
        - clientId
        - productId
      properties:
        clientId:
          description: Идентификатор клиента
          type: number
        productId:
          description: Идентификатор продукта/услуги
          type: number
          format: int64
    IncreasingParameters:
      required:
        - userType
        - sum
      properties:
        userType:
          $ref: '#/components/schemas/UserType'
        sum:
          description: Сумма для списания
          type: number
          format: int32
    DeacreasingParameters:
      required:
        - userType
        - sum
      properties:
        userType:
          $ref: '#/components/schemas/UserType'
        sum:
          description: Сумма для списания
          type: number
          format: int32
    UserType:
      description: >-
        Тип пользователя системы: клиент или поставщик
      type: string
      enum:
        - client # Списание
        - debit # Пополнение